### ISSUE TITLE
add support for ordered query params

### ISSUE THREAD

**Issue by lancejpollard** [segment-boneyard/load-pixel#2]
some api's depend on parameters being in a specific order, but since iterating object keys in a specific order isn't part of the js spec (i don't think), should we add support for passing a straight string, or an array, to the returned function?

``` js
var load = require('load-pixel')('http://example.com/');
load({ key: 'value' });
load('key=value');
load([ [ 'key', 'value' ] ]);
```

http://stackoverflow.com/questions/3122548/iterating-javascript-object-properties-and-arrays-with-for-in-when-ordering-is

/cc @yields @ianstormtaylor

**Comment by ianstormtaylor** [comment]
i think for 1-level deep objects all of the implementations keep them ordered, so we dont need to end up caring for that

they only unorder on the second+ levels of nesting

**Comment by lancejpollard** [comment]
nice, good to know
